name: Rolling Update
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
  pull_request:
  #schedule:
    # Daily
    #- cron: '0 8 * * *'
    # Every 3 days
    #- cron: '0 0 */3 * *'
jobs:
  build:
    name: Rolling update
    runs-on: ubuntu-latest
    steps:
      - name: Prepare command depends
        run: |
          sudo npm i -g @vercel/ncc
      - uses: actions/checkout@v2
      - name: "Yarn Install"
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: "Yarn Release"
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: release # will run `yarn test` command
      - name: "Patch code" # patch getUploadChunkSize, getRetryLimit, getRetryMultiplier, getInitialRetryIntervalInMilliseconds, createHttpClient
        run: |
          sed -i 's|8 \* 1024 \* 1024|512 * 1024|g' dist/index.js
          sed -i 's|return 5;|return 10000;|g' dist/index.js
          sed -i 's|return 1\.5;|return 1\.0;|g' dist/index.js
          sed -i 's|return 3000;|return 2000;|g' dist/index.js
          sed -i 's| \* retryCount||g' dist/index.js
          perl -0777 -i.original -pe 's/config_variables_1\.getRuntimeToken\(\)\)\n.*\]/config_variables_1\.getRuntimeToken\(\)\)\]\, \{socketTimeout: 12000\}/g' dist/index.js
          rm dist/index.js.original

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Setup Git
        run: |
          git config core.autocrlf false
          git config --local user.email "buildworker@misty.moe"
          git config --local user.name "NyaMistyBuildWorker"
          git diff-index HEAD
          git diff
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Commit files
        run: |
          if git diff-index --quiet HEAD; then 
            # Working directory clean
            echo "No changes, have a good day~"
          else 
            # Uncommitted changes
            git commit -m "AutoUpdate-${{ steps.date.outputs.date }}" -a
            git tag -f -a -m "Nightly-${{ steps.date.outputs.date }}" nightly
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
          force: true